name: E2E Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create TyranoStudio directory structure
      run: |
        mkdir -p ~/TyranoStudio_mac_std_v603/myprojects
        mkdir -p ~/TyranoStudio_mac_std_v603/system_master/tyranoscript_ja/data/scenario
        mkdir -p ~/TyranoStudio_mac_std_v603/system_master/tyranoscript_ja/data/bgimage
        mkdir -p ~/TyranoStudio_mac_std_v603/system_master/tyranoscript_ja/data/fgimage
        mkdir -p ~/TyranoStudio_mac_std_v603/system_master/tyranoscript_ja/data/bgm
        mkdir -p ~/TyranoStudio_mac_std_v603/system_master/tyranoscript_ja/data/sound
        mkdir -p ~/TyranoStudio_mac_std_v603/system_master/tyranoscript_ja/data/video
        mkdir -p ~/TyranoStudio_mac_std_v603/system_master/tyranoscript_ja/data/system
        mkdir -p ~/TyranoStudio_mac_std_v603/system_master/tyranoscript_ja/data/image
        mkdir -p ~/TyranoStudio_mac_std_v603/system_master/tyranoscript_ja/data/others

    - name: Run E2E tests
      run: |
        python test_e2e.py

    - name: Test summary
      if: always()
      run: |
        echo "E2E tests completed"